# This is a basic workflow to help you get started with Actions

name: Multiple Jobs Send Email V3 Try

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      ordernumber:
        description: 'Order number to process'
        required: true
        default: '8899'
      email:
        description: 'Email address'
        required: true
        default: 'abhishek777@gmail.com'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Succeed
        run: echo -e "Step Succeed"

      - name: Succeed Two
        run: |
          echo -e "Line One"
          echo -e "Line Two"
          echo "Line Three"
          echo "Line Four"

  notify:
    needs: build
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Native Job
        id: native_job
        run: |
          echo "Status of 'build' job = "
          echo "${{needs.build.result}}"

      - name: Install mutt
        run: sudo apt update && sudo apt install -y mutt

      - name: Setup mutt
        run: |
          cat << EOF > ~/.muttrc
          set smtp_url = "smtps://abhishek777@smtp.gmail.com"
          set smtp_pass = ${{ secrets.EMAIL_PASSWORD }}
          set from = ${{ secrets.EMAIL_USERNAME }}
          set realname = "Abhishek"
          EOF

      - name: Send email
        env:
          REPODATA: "Repo: ${{ github.repository }} Workflow: ${{ github.workflow }} Run: ${{ github.run_number }}"
          GITHUB_RUN_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        run: |
          echo -e "Job URL for Order:${{github.event.inputs.ordernumber}}\n${GITHUB_RUN_URL}\nJob Status: ${{needs.build.result}}\n\nRegards\nTest Team"| \
          echo -e "\nJOB URL for Order:${{github.event.inputs.ordernumber}}\n${GITHUB_RUN_URL}\nJob Status: ${{needs.build.conclusion}}\n\nRegards\nTest Team"| \
          mutt \
            -s "Job: ${REPODATA}" \
            -- "${{ github.event.inputs.email }}"
